Resources:

  DemoKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: MyDemoKeyPair

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-0d406e26e5ad4de53
      InstanceType: t2.micro
      KeyName: !Ref DemoKeyPair
      SecurityGroups:
        - !Ref SSHSecurityGroup
      Tags:
        - Key: Environment
          Value: Test
        - Key: Name
          Value: CloudFormation-Ec2

  # an elastic IP for our instance
#  MyEIP:
#    Type: AWS::EC2::EIP
#    Properties:
#      InstanceId: !Ref MyInstance

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
