version: '3'
services:
  jenkins:
    image: jenkins/jenkins:latest
    ports:
    - 8080:8080
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    user: root
