# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: App Demo CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'app/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'app/**'
      - '.github/workflows/**'

jobs:
  app-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven dependencies
      run: mvn install

    - name: Run tests
      run: mvn verify

#    - name: Build with Maven
#      run: mvn -B package --file app/pom.xml

  image-build:

    runs-on: ubuntu-latest
    needs:
      - app-build

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag demo:$(date +%s)
