name: App Demo CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'app/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'app/**'
      - '.github/workflows/**'

jobs:
  build-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Install Maven dependencies
      run: mvn install --file app/pom.xml

    - name: Run tests
      run: mvn verify --file app/pom.xml

    - name: Copy Jar file
      run: mv app/target/demo-1.0.0.jar app.jar

    - uses: actions/upload-artifact@master
      with:
        name: jar-file
        path: app.jar

  build-image:

    runs-on: ubuntu-latest
    needs:
      - build-app

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - uses: actions/download-artifact@master
      with:
        name: jar-file
        path: app.jar

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-app
        IMAGE_TAG: demo_image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --file Dockerfile
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#      run: docker build . --file Dockerfile --tag demo:$(date +%s)
