name: App Demo CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'infra/**'
      - '.github/workflows/create-stack.yaml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'infra/**'
      - '.github/workflows/create-stack.yaml'

jobs:
  deploy-stack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: DemoStack
        template: infra/stack.yaml
